version: '3'

services:
  generator:
    build:
      context: .
      dockerfile: generator/Dockerfile
    ports:
      - "9080:8080"
    restart: always

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "9081:8080"
    restart: always
    depends_on:
      - generator
